services:
    aerial_ship_steel_mq.form.type.project:
        class: AerialShip\SteelMqBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: project }

    aerial_ship_steel_mq.form.type.queue:
        class: AerialShip\SteelMqBundle\Form\Type\QueueType
        tags:
            - { name: form.type, alias: queue }

    aerial_ship_steel_mq.form.type.message:
        class: AerialShip\SteelMqBundle\Form\Type\MessageType
        tags:
            - { name: form.type, alias: message }

    aerial_ship_steel_mq.form.type.message_collection:
        class: AerialShip\SteelMqBundle\Form\Type\MessageCollectionType
        tags:
            - { name: form.type, alias: message_collection }

    aerial_ship_steel_mq.form.type.project_collaborator:
        class: AerialShip\SteelMqBundle\Form\Type\ProjectCollaboratorType
        tags:
            - { name: form.type, alias: project_collaborator }

    aerial_ship_steel_mq.form.type.share_project:
        class: AerialShip\SteelMqBundle\Form\Type\ShareProjectType
        tags:
            - { name: form.type, alias: share_project }
