services:
    aerial_ship_steel_mq.manager.project_role:
        class: AerialShip\SteelMqBundle\Services\Manager\ProjectRoleManager
        arguments:
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:ProjectRole')"
            - @security.context
            - @aerial_ship_steel_mq.user_provider

    aerial_ship_steel_mq.manager.project:
        class: AerialShip\SteelMqBundle\Services\Manager\ProjectManager
        arguments:
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:Project')"
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:ProjectRole')"
            - @security.context
            - @aerial_ship_steel_mq.user_provider

    aerial_ship_steel_mq.manager.queue:
        class: AerialShip\SteelMqBundle\Services\Manager\QueueManager
        arguments:
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:Queue')"
            - @security.context
            - @aerial_ship_steel_mq.defaulter.queue

    aerial_ship_steel_mq.manager.message:
        class: AerialShip\SteelMqBundle\Services\Manager\MessageManager
        arguments:
            - @validator
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:Message')"
            - @aerial_ship_steel_mq.defaulter.message
            - @aerial_ship_steel_mq.defaulter.get_message
            - @aerial_ship_steel_mq.defaulter.release_message

    aerial_ship_steel_mq.manager.subscriber:
        class: AerialShip\SteelMqBundle\Services\Manager\SubscriberManager
        arguments:
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:Subscriber')"
            - @security.context
