services:
    aerial_ship_steel_mq.security.authenticator:
        class: AerialShip\SteelMqBundle\Security\Core\Authentication\TokenAuthenticator
        arguments:
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:ProjectRole')"
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:User')"

    aerial_ship_steel_mq.security.user_provider:
        class: AerialShip\SteelMqBundle\Security\Core\User\SteelMqUserProvider
        arguments:
            - "@=service('doctrine').getManager().getRepository('AerialShipSteelMqBundle:User')"
