tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

filter:
    excluded_paths:
        - 'app/*'

before_commands:
    - mysql -e 'create database steelmq;'

build:
    environment:
        timezone: 'Europe/Oslo'
        node: '0.10.29'
    dependencies:
        override:
            - npm install uglify-js
            - npm install uglifycss
            - npm install jscs
            - export PATH=`pwd`/node_modules/.bin:$PATH
            - curl http://www.phing.info/get/phing-latest.phar -o phing.phar
            - chmod u+x phing.phar
            - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar
            - chmod u+x php-cs-fixer.phar
            - mysql -e 'create database steelmq;'
            - composer --prefer-source --dev --no-interaction -vvv install
            - php phing.phar deploy
    project_setup:
        before:
    tests:
        before:
            -
                command: php phing.phar test
                coverage:
                    file: build/logs/coverage.clover.xml
                    format: php-clover

build_failure_conditions:
    - 'elements.rating(<= F).exists'
    - 'issues.label("unused-code").new.exists'
