tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

filter:
    excluded_paths:
        - 'app/*'
        - 'src/AerialShip/SteelMqBundle/Tests/*'

before_commands:
    - mysql -e 'create database steelmq;'
