language: php

php:
    - "5.4"

cache:
    directories:
        - vendor
        
before_script:
    - npm install uglify-js
    - npm install uglifycss
    - npm install jscs
    - mysql -e 'create database steelmq;'
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev --no-interaction install

script:
    - bin/phing deploy
    - bin/phing test

after_script:
    - php bin/coveralls -v
