aerial_ship_steel_mq_api:
    resource: "@AerialShipSteelMqBundle/Controller/Api"
    type: annotation
    defaults: { "_decoder": "json", _format: "json", "slash": "/" }
    requirements:
        slash: /|

aerial_ship_steel_mq_api_raw:
    resource: "@AerialShipSteelMqBundle/Controller/ApiRaw"
    type: annotation
    defaults: { _format: "json", "slash": "/"  }
    requirements:
        slash: /|

aerial_ship_steel_mq_html:
    resource: "@AerialShipSteelMqBundle/Controller/Html"
    type: annotation
    defaults: { "_format": "html", "slash": "/" }
    requirements:
        slash: /|
